[package]
name = "crabstructor_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
quote = "1"
proc-macro2 = {version = "1.0.86"}
syn = { version = "2", features = ["full", "extra-traits"] }